### ISSUE TITLE
Issue when running benchmark from within devcontainer

### ISSUE THREAD

**Issue by francocipollone** [Ekumen-OS/lambkin#55]
## Bug description

I am trying to use the available devcontainer as a development environment. As such, I'd like to run the benchmarks from within the container.  However when trying to run `cartrographer_ros` benchmark I am facing some issue which I think are related to dependencies being installed in the container. 

I followed two paths:

### How to reproduce

1. Create a container using root's devcontainer definition: https://github.com/ekumenlabs/lambkin/tree/main/.devcontainer
2. `colcon build` && source `install/setup.bash`
3. Having magazingo dataset in the folder:
  ```
  rosrun cartographer_ros_benchmarks magazino_benchmark.robot
  ```

**Expected behavior**
benchmark should run flawlessly.

**Actual behavior**
Benchmark "runs" and fails due to that the framework doesn't find the generated map file. Digging a bit I realized it is because the cartographer package hasn't been installed. (I roslaunched the launch file there proposed to have a more verbose input)

**I guess this behavior is expected as the main devcontainer is expected to be used for lambkin dev and tackling repository level issues.** Am I ok?

### How to reproduce

1. Create a container using benchmarks/cartographer's devcontainer definition: https://github.com/ekumenlabs/lambkin/tree/main/src/benchmarks/cartographer_ros_benchmarks/.devcontainer
2. `catkin_make`  (here colcon isn't found in the system) && `source devel/setup.bash`
3. Having magazingo dataset in the folder:
```
rosrun cartographer_ros_benchmarks magazino_benchmark.robot 
```

**Expected behavior**
the benchmark should run flawlessly.

**Actual behavior**
It breaks before even starting the benchmark:
```
/usr/bin/env: ‘shepherd’: No such file or directory
```

Is this an issue related to package renaming?

--------------------------------------------------------------------------------------------------------

It is possible that I am not running the benchmarks correctly, if so please enlighten my path.

**Comment by hidmic** [comment]
Same as for #51, the way LAMBKIN does containerization has changed so much that I hardly think this will still apply.
