### ISSUE TITLE
Create a ROS /tf_static publisher

### ISSUE THREAD

**Issue by nahueespinosa** [Ekumen-OS/lambkin#6]
## Description

There is a [historical problem](https://answers.ros.org/question/207551/how-to-save-static-transforms-in-bag-files/?answer=207647#post-id-207647) with ROS bags playing `tf_static` or latched topics in general. Some publicly available datasets (e.g. [Magazino](https://google-cartographer-ros.readthedocs.io/en/latest/data.html#magazino)) do use `tf_static` and we need to be able to reproduce those datasets without having to manually add [static_transform_publishers](http://wiki.ros.org/tf#static_transform_publisher) to a launch file.

## Definition of done
Write a script that checks if a bag contains any latched topics and creates publishers for them. Add it to the benchmark pipeline.

**Comment by hidmic** [comment]
I don't think we'll ever do this. OSRF is dropping ROS 1 support in ~8 months. Closing.
